-- Explore all objects in the database
SELECT * FROM INFORMATION_SCHEMA.TABLES

-- Explore all columns in the database
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers';

SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'gold.dim_products'

-- Explore All countries our customers come from.
SELECT DISTINCT country FROM gold.dim_customers;

-- Explore All categories "The major divisions"
SELECT DISTINCT category,subcategory,product_name FROM gold.dim_products
ORDER BY 1,2,3;

-- Find the date of the first and last order
-- How many years of sales are available
SELECT 
MIN(order_date) AS first_order_date,
MAX(order_date) AS last_order_date,
DATEDIFF(year, MIN(order_date), MAX(order_date)) AS order_range_years
FROM gold.fact_sales;

-- Find the youngest and oldest customer
SELECT
MIN(birthdate) AS oldest_birthdate,
MAX(birthdate) AS youngest_birthdate,
DATEDIFF(year, MIN(birthdate), GETDATE()) AS oldest_age,
DATEDIFF(year, MAX(birthdate), GETDATE()) AS youngest_age
FROM gold.dim_customers;

--Find the total Sales
SELECT SUM(sales_amount) AS total_sales FROM gold.fact_sales;

--Find how many items are sold
SELECT SUM(quantity) AS total_quantity FROM gold.fact_sales;

--Find the average selling price
SELECT AVG(price) AS avg_price FROM gold.fact_sales;

--Find the total number of orders
SELECT COUNT(order_number) AS total_order FROM gold.fact_sales;
SELECT COUNT(DISTINCT order_number) AS total_order FROM gold.fact_sales;

--Find the total number of products
SELECT COUNT(product_id) AS total_products FROM gold.dim_products;

--Find the total number of customers
SELECT COUNT(customer_id) AS total_customers FROM gold.dim_customers;

--Find the total number of customers that has placed an order
SELECT COUNT(DISTINCT customer_key) AS n_customers FROM gold.fact_sales;

-- Generate a report that shows all key metricts of the business

SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity' AS measure_name, SUM(quantity) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Average Price', AVG(price) AS avg_price FROM gold.fact_sales
UNION ALL
SELECT 'Total Nr.Orders', COUNT(DISTINCT order_number) FROM gold.fact_sales
UNION ALL
SELECT 'Total Nr. Products', COUNT(product_name) FROM gold.dim_products
UNION ALL
SELECT 'Total Nr. Customers', COUNT(customer_key) FROM gold.dim_customers;

/*----------------------------------------------------------------------------------*/

-- Find total customers by countries
SELECT 
country, 
COUNT(customer_key) AS total_customers 
FROM gold.dim_customers 
GROUP BY country
ORDER BY total_customers DESC;

-- Find total customers by gender
SELECT
gender,
COUNT(customer_key) AS total_gender
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_gender DESC;

-- Find total products by category
SELECT
category,
COUNT(product_key) AS total_category
FROM gold.dim_products
GROUP BY category
ORDER BY total_category DESC;

-- What is the average costs in each category?
SELECT
category,
AVG(cost) AS avg_cost_by_category
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost_by_category DESC;

-- What is the total revenue generated for each category?
SELECT
p.category,
SUM((s.price * s.quantity) - (p.cost * s.quantity)) AS revenue_by_category
FROM gold.fact_sales AS s
LEFT JOIN
gold.dim_products AS p
ON p.product_key = s.product_key
GROUP BY p.category;

-- Find total revenue is generated by each customer
SELECT
s.customer_key,
SUM((s.price * s.quantity) - (p.cost * s.quantity)) AS revenue_by_category
FROM gold.fact_sales AS s
LEFT JOIN
gold.dim_products AS p
ON p.product_key = s.product_key
LEFT JOIN
gold.dim_customers AS c
ON s.customer_key = c.customer_id
GROUP BY s.customer_key
ORDER BY s.customer_key DESC;

-- What is the distribution of sold items across countries?
SELECT
c.country,
SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers AS c
ON c.customer_key = f.customer_key
GROUP BY
c.country
ORDER BY total_sold_items DESC;

-- which 5 products generate the highest revenue?
SELECT TOP 5
p.product_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_products AS p
ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC;


-- what are the 5 worst-performing products in terms of sales?
SELECT TOP 5
p.product_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_products AS p
ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue;

-- WINDOW FUNCTIONS => For more flexible and complex queries with extra details
SELECT *
FROM (
	SELECT
	p.product_name,
	SUM(f.sales_amount) AS total_revenue,
	RANK() OVER(ORDER BY SUM(f.sales_amount) DESC) AS rank_products
	FROM gold.fact_sales AS f
	LEFT JOIN gold.dim_products AS p
	ON p.product_key = f.product_key
	GROUP BY p.product_name)t
WHERE rank_products <= 5

SELECT TOP 3
c.customer_key,
c.first_name,
c.last_name,
COUNT(DISTINCT order_number) AS total_orders
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
ON c.customer_key = f.customer_key
GROUP BY
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_orders

SELECT
YEAR(order_date) AS order_year,
SUM(sales_amount) AS total_sales,
COUNT(DISTINCT customer_key) AS total_customers,
SUM(quantity) AS total_quantity
FROM gold.fact_sales
WHERE order_date IS NOT NULL
GROUP BY YEAR(order_date)
ORDER BY YEAR(order_date)

SELECT
MONTH(order_date) AS order_year,
SUM(sales_amount) AS total_sales,
COUNT(DISTINCT customer_key) AS total_customers,
SUM(quantity) AS total_quantity
FROM gold.fact_sales
WHERE order_date IS NOT NULL
GROUP BY MONTH(order_date)
ORDER BY MONTH(order_date)

